name: firebase_dart_ui
description: Firebase UI wrapper
version: 0.0.1
#homepage: https://www.example.com
#author: Warren Strange <email@example.com>

environment:
  sdk: '>=2.0.0-dev.15.0 <2.0.0'

dependencies:
  angular:  5.0.0-alpha+2
  firebase: ^4.2.0+1
  js: ^0.6.0


dev_dependencies:
  angular_test: ^1.0.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0

dependency_overrides:
  # Necessary with angular: 5.0.0-alpha+1 dependency.
  analyzer: ^0.31.0-alpha.1
transformers:
- angular:
    entry_points:
      - example/web/main.dart
      - test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc
